name: CI
on: push

jobs:
  unit-test:
    runs-on: windows-latest
    env:
      RUSTFLAGS: -C instrument-coverage
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: llvm-tools-preview
          override: true
      - name: Run tests
        run: cargo test -- --color always
        env:
          LLVM_PROFILE_FILE: "./cov/cov-%p-%m.profraw"
      - name: Install grcov
        run: |
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-pc-windows-msvc.zip > grcov.zip
          unzip ./grcov.zip
          ./grcov --version
        shell: bash
      - name: Generate coverage results
        run: ./grcov.exe ./cov/*.profraw -s src --binary-path ./target/debug/ -t lcov --ignore-not-existing --ignore '/*' -o ./cov/lcov.info
      - uses: codecov/codecov-action@v2
        with:
          files: ./cov/lcov.info
      - uses: actions/upload-artifact@v3
        with:
          path: ./cov/lcov.info
